apiVersion: v1
kind: Service
metadata:
  name: {{ include "comethru.name" . }}-frontend
  labels:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
    component: frontend