{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comethru-chart.fullname" . }}-nginx
  labels:
    {{- include "comethru-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "comethru-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}