{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comethru.name" . }}-nginx
  labels:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
    component: nginx
{{- end }}